#!/usr/bin/env python3
"""Generate the LaTeX book from the JSON problem banks.

Reads   content/topics.json          -- the ordered list of the 20 topics
        content/bank/topic-NN.json   -- lesson + 44 problems for each topic

Writes  book/topics/topic-NN.tex     -- lesson, Module 1 (22), Module 2 (22)
        book/solutions/sol-NN.tex    -- worked solution for all 44
        book/generated/answerkey.tex -- the book-wide answer key
        book/generated/topics.tex    -- \\input lines consumed by main.tex
        book/generated/solutions.tex -- \\input lines consumed by main.tex

Everything under book/generated/, book/topics/ and book/solutions/ is a build
product: edit the JSON, never the .tex.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BANK = ROOT / "content" / "bank"
TOPICS = ROOT / "content" / "topics.json"
OUT_TOPIC = ROOT / "book" / "topics"
OUT_SOL = ROOT / "book" / "solutions"
OUT_GEN = ROOT / "book" / "generated"

BLOCK_ENV = {
    "concept": "satconcept",
    "formula": "satformula",
    "trap": "sattrap",
    "strategy": "satstrategy",
    "worked": "satworked",
}

BANNER = "% GENERATED by tools/gen_book.py -- do not edit; edit content/bank/*.json\n"


def esc(text: str) -> str:
    """The JSON already carries LaTeX, so only guard the characters that are
    unambiguously literal in prose."""
    return text


def render_lesson(bank: dict) -> str:
    out = [esc(bank["lesson"]["intro"]), ""]
    for block in bank["lesson"]["blocks"]:
        kind = block["kind"]
        if kind == "section":
            out.append(f"\\section*{{{esc(block['title'])}}}")
            out.append(esc(block["body"]))
        else:
            env = BLOCK_ENV[kind]
            out.append(f"\\begin{{{env}}}[{esc(block['title'])}]")
            out.append(esc(block["body"]))
            out.append(f"\\end{{{env}}}")
        out.append("")
    return "\n".join(out)


def render_problem(p: dict) -> str:
    out = [f"% {p['id']}",
           f"\\begin{{satq}}{{{p['difficulty']}}}{{{p['type']}}}"]
    if p.get("figure"):
        out.append("\\begin{satfigure}")
        out.append(p["figure"])
        out.append("\\end{satfigure}")
    out.append(esc(p["stem"]))
    if p["type"] == "MC":
        cmd = "satchoiceswide" if p.get("wide") else "satchoices"
        args = "".join("{" + esc(c) + "}" for c in p["choices"])
        out.append(f"\\{cmd}{args}")
    else:
        out.append("\\satgridin")
    out.append("\\end{satq}")
    return "\n".join(out)


def render_topic(bank: dict) -> str:
    n = bank["number"]
    out = [BANNER,
           f"\\sattopic{{{n}}}{{{esc(bank['topic'])}}}{{{esc(bank['domain'])}}}",
           "",
           render_lesson(bank),
           ""]

    problems = sorted(bank["problems"], key=lambda p: p["n"])
    m1 = [p for p in problems if p["module"] == 1]
    m2 = [p for p in problems if p["module"] == 2]

    out.append("\\satmodulehead{1}{}{}")
    out.append("\\begin{satproblems}")
    out.extend(render_problem(p) for p in m1)
    out.append("\\end{satproblems}")

    out.append("")
    out.append("\\satmodulehead{2}{}{}")
    out.append("\\begin{satproblems}")
    out.extend(render_problem(p) for p in m2)
    out.append("\\end{satproblems}")
    out.append("")
    return "\n".join(out)


def render_solutions(bank: dict) -> str:
    n = bank["number"]
    out = [BANNER,
           f"\\section*{{Topic {n:02d} \\textemdash\\ {esc(bank['topic'])}}}",
           f"\\addcontentsline{{toc}}{{section}}"
           f"{{Topic {n:02d} \\textemdash\\ {esc(bank['topic'])}}}",
           ""]

    problems = sorted(bank["problems"], key=lambda p: p["n"])
    for mod, label in ((1, "Module 1"), (2, "Module 2")):
        out.append(f"\\subsection*{{{label}}}")
        for p in (q for q in problems if q["module"] == mod):
            answer = p["answer"]
            if p["type"] == "MC":
                answer = f"{p['answer']}"
            shown = p["n"] if p["module"] == 1 else p["n"] - 22
            out.append(f"\\satsolhead{{{shown}}}{{{esc(answer)}}}")
            if p.get("steps"):
                out.append("\\begin{satsteps}")
                out.extend(f"  \\item {esc(s)}" for s in p["steps"])
                out.append("\\end{satsteps}")
            out.append(esc(p["solution"]))
            out.append("")
    return "\n".join(out)


def render_answer_key(banks: list[dict]) -> str:
    out = [BANNER,
           "\\chapter*{Answer Key}",
           "\\addcontentsline{toc}{chapter}{Answer Key}",
           "\\markboth{Answer Key}{Answer Key}",
           ""]
    for bank in banks:
        n = bank["number"]
        out.append(f"\\subsection*{{Topic {n:02d} \\textemdash\\ "
                   f"{esc(bank['topic'])}}}")
        problems = sorted(bank["problems"], key=lambda p: p["n"])
        cols = 8
        colspec = ("r@{\\hspace{5pt}}l@{\\hspace{16pt}}" * (cols - 1)
                   + "r@{\\hspace{5pt}}l")
        for mod in (1, 2):
            out.append(f"\\satkeymodule{{{mod}}}")
            out.append("\\satkeytable{%")
            out.append("\\noindent\\begin{longtable}{@{}" + colspec + "@{}}")
            cells = []
            for p in (q for q in problems if q["module"] == mod):
                ans = p["answer"].replace("&", "\\&")
                shown = p["n"] if mod == 1 else p["n"] - 22
                cells.append(
                    f"\\textbf{{\\color{{satgrey}}{shown}}} & {ans}")
            for i in range(0, len(cells), cols):
                row = cells[i:i + cols]
                row += [" & "] * (cols - len(row))
                out.append(" & ".join(row) + " \\\\")
            out.append("\\end{longtable}}")
        out.append("")
    return "\n".join(out)


def main() -> int:
    if not TOPICS.exists():
        print("content/topics.json is missing", file=sys.stderr)
        return 1
    order = json.loads(TOPICS.read_text())["topics"]

    for d in (OUT_TOPIC, OUT_SOL, OUT_GEN):
        d.mkdir(parents=True, exist_ok=True)

    banks: list[dict] = []
    includes_topics: list[str] = []
    includes_sols: list[str] = []
    missing: list[int] = []
    part_no = 0
    current_domain = None

    for entry in order:
        n = entry["number"]
        path = BANK / f"topic-{n:02d}.json"
        if not path.exists():
            missing.append(n)
            continue
        bank = json.loads(path.read_text())
        banks.append(bank)

        # a part divider opens each new domain
        if bank["domain"] != current_domain:
            current_domain = bank["domain"]
            part_no += 1
            includes_topics.append(
                f"\\satpart{{{part_no}}}{{{esc(current_domain)}}}")

        (OUT_TOPIC / f"topic-{n:02d}.tex").write_text(render_topic(bank))
        (OUT_SOL / f"sol-{n:02d}.tex").write_text(render_solutions(bank))
        includes_topics.append(f"\\input{{topics/topic-{n:02d}}}")
        includes_sols.append(f"\\input{{solutions/sol-{n:02d}}}")

    (OUT_GEN / "answerkey.tex").write_text(render_answer_key(banks))
    (OUT_GEN / "topics.tex").write_text(BANNER + "\n".join(includes_topics) + "\n")
    (OUT_GEN / "solutions.tex").write_text(BANNER + "\n".join(includes_sols) + "\n")

    print(f"generated {len(banks)} topic(s), "
          f"{sum(len(b['problems']) for b in banks)} problems")
    if missing:
        print("missing banks for topics: "
              + ", ".join(f"{m:02d}" for m in missing))
    return 0


if __name__ == "__main__":
    sys.exit(main())
